### ISSUE TITLE
Concept mapping 3-240-215 calf

### ISSUE THREAD

**Issue by chrzyki** [intercontinental-dictionary-series/ids#23]
https://ids.clld.org/valuesets/3-240-215 seems to be not the 'calf' but rather the 'calf of leg' (compare https://ids.clld.org/valuesets/4-370-215). Thanks to @AnnikaTjuka for reporting this.

**Comment by Bibiko** [comment]
I'm **NOT** a specialist on this language, but if one compares:
calf: http://cal.huc.edu/oneentry.php?lemma=%28gl%20N&cits=all
foot: http://cal.huc.edu/oneentry.php?lemma=rgl%20N&cits=all
it **could be** a kind of a homonym (maybe due to transliteration).

**Comment by AnnikaTjuka** [comment]
Interesting! Thanks, @Bibiko. I think then we can leave it as is.

**Comment by chrzyki** [comment]
Yes, thanks for investigating @Bibiko!
