### ISSUE TITLE
Move repos to intercontinental-dictionary-series org

### ISSUE THREAD

**Issue by xrotwang** [intercontinental-dictionary-series/ids#9]
We have the https://github.com/intercontinental-dictionary-series org now to manage additions to IDS. I think it makes sense to move this repos there as well.
@LinguList @chrzyki  Any objections?

**Comment by Bibiko** [comment]
no objections as long as the branch 'bibiko' does not disappear :)

**Comment by xrotwang** [comment]
@Bibiko  Hm. I don't like long-lived branches. They tend to become un-mergeable - and at that point lose any meaning. What are you using this branch for?

**Comment by LinguList** [comment]
No, this is much better!

**Comment by chrzyki** [comment]
No objections, sounds very good and reasonable.
